### ISSUE TITLE
function disregards the direction logic & also enters an enters infinite loop

### ISSUE THREAD

**Issue by armantorkzaban** [dartclub/turf_equality#8]
https://github.com/dartclub/turf_equality/blob/50f121bba2097b411bf11ddf89ed77a6df03d8a2/lib/src/turf_equality_base.dart#L118-L124
in case the comparison of the first Positions after on LineString's coordinate is reversed produces false, because of the direction flag we create an infinite loop that keeps flipping coordinates and comparing them.

**Comment by lukas-h** [comment]
Is this resolved?

**Comment by armantorkzaban** [comment]
it's resolved in [c9a2ef4](https://github.com/dartclub/turf_equality/commit/c9a2ef4fd131ca1cfef0eed0454e7814092e74dd)
